// A list of all actions in the system.
import { createTypes } from 'reduxsauce';

export default createTypes(`

  SUPPLIERS_REQUEST
  SUPPLIERS_RECEIVE

  SUPPLIERS_LAST5_REQUEST
  SUPPLIERS_LAST5_RECEIVE

  SUPPLIERS_ADD_REQUEST
  SUPPLIERS_ADD_RECEIVE

  SUPPLIERS_UPDATE_REQUEST
  SUPPLIERS_UPDATE_RECEIVE

  SUPPLIERS_DELETE_REQUEST
  SUPPLIERS_DELETE_RECEIVE

`);
