// A list of all actions in the system.
import { createTypes } from 'reduxsauce';

export default createTypes(`

  SUPPLIERS_REQUEST
  SUPPLIERS_RECEIVE

  PRODUCTS_REQUEST
  PRODUCTS_RECEIVE

  SUPPLIERS_LAST5_REQUEST
  SUPPLIERS_LAST5_RECEIVE

  PRODUCTS_LAST5_REQUEST
  PRODUCTS_LAST5_RECEIVE

  SUPPLIER_ADD_REQUEST
  SUPPLIER_ADD_RECEIVE 

  PRODUCT_ADD_REQUEST
  PRODUCT_ADD_RECEIVE

  SUPPLIER_EDIT_REQUEST
  SUPPLIER_EDIT_RECEIVE

  PRODUCT_EDIT_REQUEST
  PRODUCT_EDIT_RECEIVE

  SUPPLIER_DELETE_REQUEST
  SUPPLIER_DELETE_RECEIVE

  PRODUCT_DELETE_REQUEST
  PRODUCT_DELETE_RECEIVE

  MODAL_OPEN
  MODAL_CLOSE

`);
